export const SET_ACTIVE_ITEM = "SET_ACTIVE_ITEM";
export const SET_ACTIVE_COMPONENT = "SET_ACTIVE_COMPONENT";
export const SET_OPEN_DRAWER = "SET_OPEN_DRAWER";
export const SET_OPEN_COMPONENT_DRAWER = "SET_OPEN_COMPONENT_DRAWER";